// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: modules/auth/authPb/authPb.proto

package go_shop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_modules_auth_authPb_authPb_proto_rawDescGZIP(), []int{0}
}

type CredentialReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialReq) Reset() {
	*x = CredentialReq{}
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialReq) ProtoMessage() {}

func (x *CredentialReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialReq.ProtoReflect.Descriptor instead.
func (*CredentialReq) Descriptor() ([]byte, []int) {
	return file_modules_auth_authPb_authPb_proto_rawDescGZIP(), []int{1}
}

func (x *CredentialReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type CredentialRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialRes) Reset() {
	*x = CredentialRes{}
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialRes) ProtoMessage() {}

func (x *CredentialRes) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialRes.ProtoReflect.Descriptor instead.
func (*CredentialRes) Descriptor() ([]byte, []int) {
	return file_modules_auth_authPb_authPb_proto_rawDescGZIP(), []int{2}
}

func (x *CredentialRes) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type RolesCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolesCountReq) Reset() {
	*x = RolesCountReq{}
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolesCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesCountReq) ProtoMessage() {}

func (x *RolesCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesCountReq.ProtoReflect.Descriptor instead.
func (*RolesCountReq) Descriptor() ([]byte, []int) {
	return file_modules_auth_authPb_authPb_proto_rawDescGZIP(), []int{3}
}

type RolesCountRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolesCountRes) Reset() {
	*x = RolesCountRes{}
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolesCountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesCountRes) ProtoMessage() {}

func (x *RolesCountRes) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesCountRes.ProtoReflect.Descriptor instead.
func (*RolesCountRes) Descriptor() ([]byte, []int) {
	return file_modules_auth_authPb_authPb_proto_rawDescGZIP(), []int{4}
}

func (x *RolesCountRes) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_modules_auth_authPb_authPb_proto protoreflect.FileDescriptor

const file_modules_auth_authPb_authPb_proto_rawDesc = "" +
	"\n" +
	" modules/auth/authPb/authPb.proto\"\a\n" +
	"\x05Empty\"1\n" +
	"\rCredentialReq\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\")\n" +
	"\rCredentialRes\x12\x18\n" +
	"\aisValid\x18\x01 \x01(\bR\aisValid\"\x0f\n" +
	"\rRolesCountReq\"%\n" +
	"\rRolesCountRes\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count2s\n" +
	"\x0fAuthGrpcService\x122\n" +
	"\x10CredentialSearch\x12\x0e.CredentialReq\x1a\x0e.CredentialRes\x12,\n" +
	"\n" +
	"RolesCount\x12\x0e.RolesCountReq\x1a\x0e.RolesCountResB\x1eZ\x1cgithub.com/Hayato360/go_shopb\x06proto3"

var (
	file_modules_auth_authPb_authPb_proto_rawDescOnce sync.Once
	file_modules_auth_authPb_authPb_proto_rawDescData []byte
)

func file_modules_auth_authPb_authPb_proto_rawDescGZIP() []byte {
	file_modules_auth_authPb_authPb_proto_rawDescOnce.Do(func() {
		file_modules_auth_authPb_authPb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_auth_authPb_authPb_proto_rawDesc), len(file_modules_auth_authPb_authPb_proto_rawDesc)))
	})
	return file_modules_auth_authPb_authPb_proto_rawDescData
}

var file_modules_auth_authPb_authPb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_modules_auth_authPb_authPb_proto_goTypes = []any{
	(*Empty)(nil),         // 0: Empty
	(*CredentialReq)(nil), // 1: CredentialReq
	(*CredentialRes)(nil), // 2: CredentialRes
	(*RolesCountReq)(nil), // 3: RolesCountReq
	(*RolesCountRes)(nil), // 4: RolesCountRes
}
var file_modules_auth_authPb_authPb_proto_depIdxs = []int32{
	1, // 0: AuthGrpcService.CredentialSearch:input_type -> CredentialReq
	3, // 1: AuthGrpcService.RolesCount:input_type -> RolesCountReq
	2, // 2: AuthGrpcService.CredentialSearch:output_type -> CredentialRes
	4, // 3: AuthGrpcService.RolesCount:output_type -> RolesCountRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_modules_auth_authPb_authPb_proto_init() }
func file_modules_auth_authPb_authPb_proto_init() {
	if File_modules_auth_authPb_authPb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_auth_authPb_authPb_proto_rawDesc), len(file_modules_auth_authPb_authPb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_auth_authPb_authPb_proto_goTypes,
		DependencyIndexes: file_modules_auth_authPb_authPb_proto_depIdxs,
		MessageInfos:      file_modules_auth_authPb_authPb_proto_msgTypes,
	}.Build()
	File_modules_auth_authPb_authPb_proto = out.File
	file_modules_auth_authPb_authPb_proto_goTypes = nil
	file_modules_auth_authPb_authPb_proto_depIdxs = nil
}
